[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/feed"
  to = "/feed"
  status = 200

[[redirects]]
  from = "/library"
  to = "/library"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success"
  status = 200


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/getMessage/:splat"
  status = 200